### ISSUE TITLE
missing parentheses in simpletest.py

### ISSUE THREAD

**Issue by Swicano** [CedarGroveStudios/CircuitPython_NAU7802#2] opened 2023-01-13 01:28 UTC
i think this line is returning true because it is a bound method, not because the ADC is actually ready for another call

https://github.com/CedarGroveStudios/CircuitPython_NAU7802/blob/154d2192e5b8cb0e55fa0d86cfb882477723637a/examples/nau7802_simpletest.py#L42

**Comment by CedarGroveStudios** [comment] 2023-01-13 04:09
Thank you for finding this! Some preliminary tests are showing that the Cycle Ready (CR) bit in the NAU7802 power control register isn't truly indicating when ADC DATA is ready.

The good news is that by defaulting to True, the data is being passed correctly and isn't repeating previous values as would be expected if the data registers are constantly queried including between conversion cycles. I'll look at the I2C bus to see if the NAU7802 delays its response to a data read request until the current conversion cycle is complete. It's as if the chip is defaulting to a data streaming mode, although adjusting the streaming rate seems to have no effect.

I'll also look at the timing of the hardware DRDY pin to see if changes and is in cadence with the I2C data transfer.

Thanks again for finding this needle in the haystack. Hopefully the tests will reveal a solution that is synchronized with the ADC acquisition cycle.

**Comment by CedarGroveStudios** [comment] 2023-01-13 07:28
The performance issue after changing `nau7802.available` to `nau7802.available()` was caused by the NAU7802 device not updating the Cycle Ready (CR) flag reliably when the conversion rate was set to 10 samples per second (the driver and chip default). Changing the driver default to 20SPS fixed the issue. All sample rates from 20SPS to 320SPS worked nominally. I suspect that it has something to do with timing in the CircuitPython I2C register driver communication process. I'll close this issue for now since since `nau7802_simpletest.py` is working but will create an issue either for this driver or for `register` depending on some extended troubleshooting.

Thank you @Swicano!

**Closed** 2023-01-13 07:28 UTC

**Comment by CedarGroveStudios** [comment] 2023-01-13 17:11
The performance issue was linked to a racing condition caused by a fixed delay in the the driver's channel setter. Replaced the fixed delay with a loop to monitor Cycle Ready (CR). Updated the example to also use `while` instead of `if` for checking `nau7802.available()`. Reset the default conversion rate to 10SPS.
